<e> ::= <op> | <x> | <cte>
<ne> ::= <op> | <x>
<op> ::= add(<ne>,<e>) | sub(<ne>,<e>) | mul(<ne>,<e>) | pdiv(<ne>,<e>)
<x> ::= x.T[0]|x.T[1]|x.T[2]|x.T[3]|x.T[4]|x.T[5]|x.T[6]|x.T[7]|x.T[8]|x.T[9]
<cte> ::= <c><c>.<c><c>
<c>  ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9